- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install python is python3
      apt:
        name: python-is-python3
        state: present
    - name: Install python3
      apt:
        name: python3
        state: present
    - name: Install ACL
      apt:
        name: acl
        state: present
        