---
- hosts: all
  vars:
    lgsm_prereqs:
      - curl
      - wget
      - file
      - tar
      - bzip2
      - gzip
      - unzip
      - bsdmainutils
      - python3
      - util-linux
      - ca-certificates
      - binutils
      - bc
      - jq
      - tmux
      - netcat
      - lib32gcc-s1
      - lib32stdc++6
      - steamcmd
      - lib32z1
      - libsdl2-2.0-0:i386

  gather_facts: true
  become: true
  become_user: root
  tasks:
    - name: Rust Server User
      ansible.builtin.user:
        name: rustserver
        create_home: true
        home: /home/rustserver
        shell: /bin/bash
    - name: accept steam license
      debconf:
        name: "steam"
        question: "steam/question"
        value: "I AGREE"
        vtype: "select"
    - name: Add i386 arch
      command: dpkg --add-architecture i386
    - name: Install prereqs
      apt:
        name: "{{ lgsm_prereqs }}"
        update_cache: yes
        state: present
    - name: Download lgsm installer
      ansible.builtin.shell: "wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh rustserver"
      args:
        chdir: /home/rustserver
        creates: rustserver
        executable: /bin/bash       
      become: True
      become_user: rustserver
    - name: Rust Server install
      shell: "./rustserver auto-install"
      args:
        chdir: /home/rustserver
        creates: /home/rustserver/serverfiles/server/rustserver/cfg/server.cfg
        executable: /bin/bash       
      become: True
      become_user: rustserver
    - name: Rust Cron Monitor
      ansible.builtin.cron:
        name: Rust Server Monitor
        minute: "*/5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/home/rustserver/rustserver monitor > /dev/null 2>&1"
    - name: Rust Cron Update
      ansible.builtin.cron:
        name: Rust Server Update
        minute: "*/30"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/home/rustserver/rustserver update > /dev/null 2>&1"
    - name: Rust Cron Update LGSM
      ansible.builtin.cron:
        name: Rust Server Update LGSM
        minute: "0"
        hour: "0"
        day: "*"
        month: "*"
        weekday: "0"
        job: "/home/rustserver/rustserver update-lgsm > /dev/null 2>&1"
