---
- hosts: all
  gather_facts: true
  become: true
  become_user: rustserver
  tasks:
    - name: Rust server tags
      ansible.builtin.lineinfile:
        path: /home/rustserver/serverfiles/server/rustserver/cfg/server.cfg
        regexp: "^server.tags"
        line: "server.tags vanilla,biweekly"
    - name: Rust maxplayers=50
      ansible.builtin.lineinfile:
        path: /home/rustserver/lgsm/config-lgsm/rustserver/rustserver.cfg
        regexp: '^maxplayers='
        line: 'maxplayers="50"'
    - name: Rust worldsize=4000
      ansible.builtin.lineinfile:
        path: /home/rustserver/lgsm/config-lgsm/rustserver/rustserver.cfg
        regexp: '^worldsize='
        line: 'worldsize="4000"'
    - name: Rust servername
      ansible.builtin.lineinfile:
        path: /home/rustserver/lgsm/config-lgsm/rustserver/rustserver.cfg
        regexp: '^servername='
        line: 'servername="Doom Crickets | Sandbox | {{ inventory_hostname_short }}"'
