---
- hosts: all
  vars:
    rustuser: rustserver
  become: true
  become_user: "{{ rustuser }}"
  tasks:
    - name: Rust Server User
      ansible.builtin.user:
        name: "{{ rustuser }}"
      register: usr
    - name: Add Rust ownerids
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/serverfiles/server/rustserver/cfg/users.cfg"
        regexp: "^ownerid {{ item }}"
        line: "ownerid {{ item }}"
        create: yes
      loop: "{{ server_ownerids }}"
    - name: Rust set server description
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/serverfiles/server/rustserver/cfg/server.cfg"
        regexp: "^server.description"
        line: 'server.description "{{ server_description }}"'
    - name: Rust set server headerimage
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/serverfiles/server/rustserver/cfg/server.cfg"
        regexp: "^server.headerimage"
        line: "server.headerimage {{ server_headerimage }}"
    - name: Rust set server url
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/serverfiles/server/rustserver/cfg/server.cfg"
        regexp: "^server.url"
        line: "server.url {{ server_url }}"
    - name: Rust set server censorplayerlist
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/serverfiles/server/rustserver/cfg/server.cfg"
        regexp: "^server.censorplayerlist"
        line: "server.censorplayerlist {{ server_censorplayerlist }}"
    - name: Rust set server tags
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/serverfiles/server/rustserver/cfg/server.cfg"
        regexp: '^server.tags'
        line: 'server.tags "{{ server_tags }}"'
    - name: Rust allow motorboat spawns
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/serverfiles/server/rustserver/cfg/server.cfg"
        regexp: '^motorrowboat.population'
        line: 'motorrowboat.population 1'
    - name: Rust allow minicopter spawns
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/serverfiles/server/rustserver/cfg/server.cfg"
        regexp: '^minicopter.population'
        line: 'minicopter.population 1'
    - name: Rust set decay to 10% normal rate
      ansible.builtin.blockinfile:
        path: "{{ usr.home }}/serverfiles/server/rustserver/cfg/server.cfg"
        block: |
          decay.bracket_0_costfraction 0.01
          decay.bracket_1_costfraction 0.015
          decay.bracket_2_costfraction 0.02
          decay.bracket_3_costfraction 0.033
        marker: "# {mark} Adjust decay to 10%"
    - name: Rust set maxplayers
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/lgsm/config-lgsm/rustserver/rustserver.cfg"
        regexp: '^maxplayers='
        line: 'maxplayers="{{ server_maxplayers }}"'
    - name: Rust set worldsize
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/lgsm/config-lgsm/rustserver/rustserver.cfg"
        regexp: '^worldsize='
        line: 'worldsize="{{ server_worldsize }}"'
    - name: Rust set servername
      ansible.builtin.lineinfile:
        path: "{{ usr.home }}/lgsm/config-lgsm/rustserver/rustserver.cfg"
        regexp: '^servername='
        line: 'servername="{{ server_name }}"'
