---
- hosts: all
  gather_facts: true
  become: true
  become_user: rustserver
  tasks:
    - name: Rust ownerid weld
      ansible.builtin.lineinfile:
        path: /home/rustserver/serverfiles/server/rustserver/cfg/users.cfg
        regexp: '^ownerid="76561198024548959"'
        line: 'ownerid="76561198024548959"'
        create: yes
    - name: Rust ownerid redlott
      ansible.builtin.lineinfile:
        path: /home/rustserver/serverfiles/server/rustserver/cfg/users.cfg
        regexp: '^ownerid="76561198025798290"'
        line: 'ownerid="76561198025798290"'
    - name: Rust ownerid swash
      ansible.builtin.lineinfile:
        path: /home/rustserver/serverfiles/server/rustserver/cfg/users.cfg
        regexp: '^ownerid="76561198989378213"'
        line: 'ownerid="76561198989378213"'
